### ISSUE TITLE
Awesome Skill!!!! 

### ISSUE THREAD

**Issue by sdb1228** [clayton13/AlexaCanvasSkill#3]
This Alexa skill is great!  We would love for you to add your intents to the official Canvas Alexa skill repo if you have a chance! https://github.com/instructure/canvas-alexa-lambda.

**Comment by clayton13** [comment]
Thank you @sdb1228! I definitely will if the time opens up. Sorry for the delay in getting back to you, I have been on vacation away from my computer. 

My biggest blocking points for fully implementing the skill was Amazon's certification team, one has to be very careful in the names chosen to represent the skills and its intents. For example, I see that you have a "GetBlackboard" intent in your repo. I would think Amazon would flag that as copyright against Blackboard Inc.

Another concern is timing, Amazon does not give very much time for developers to process data. Making several rounds of REST calls adds up in the ping and delays. To have any hope of reliability you will need a caching system for user data. Ie. Canvas course ids, assignment ids, and user ids. I started down the path of a redis server with periodic updates.

I wish you luck and look forward to seeing the skill in the Alexa Skills Store. :)

**Comment by sdb1228** [comment]
Hey @clayton13! Thanks for the tips! The canvas-Alexa repo is the official Instructure backed canvas skill that is now hosted on the Alexa skill store. https://www.amazon.com/Instructure-Canvas/dp/B073YNGXMR/ref=nodl_
I would love your pull requests and input when you find time! It sounds like you have breath of knowledge around this fun technology.
